# Arquivo: .github/workflows/ci_cd.yml

name: CI/CD Pipeline

# Aciona o workflow em cada push na branch 'master'
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Faz o checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configura a versão do Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use a versão do Python que você está utilizando

      # Step 3: Instala as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Executa os testes
      - name: Run tests
        run: |
          pytest

  deploy:
    name: Deploy to Render
    needs: build-and-test  # Este job só será executado se o job 'build-and-test' for bem-sucedido
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Step 1: Faz o checkout do código (necessário novamente)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Dispara o deploy para o Render usando o Deploy Hook
      - name: Deploy to Render
        run: |
            curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "usr-crfllg08fa8c73d87edg"}' \
            https://api.render.com/v1/services/usr-crfllg08fa8c73d87edg/deploys